[_]
schema-version = "0.2"
id = "io.buildpacks.ibdb"
name = "InteractiveBrokers Products Database"
version = "1.0.0"

[io.buildpacks]
exclude = []
include = ["app"]

[[io.buildpacks.build.env]]
name="GOOGLE_FUNCTION_SIGNATURE_TYPE"
value="http"

[[io.buildpacks.build.env]]
name="GOOGLE_FUNCTION_TARGET"
value="main"
